repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: cspell
        name: cspell
        entry: npx cspell
        language: system
        types: [text]
        args: [--config, .cspell.json]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.403
    hooks:
      - id: pyright
        additional_dependencies: [
          # Core dependencies
          numpy,
          click,
          bson,
          pytest,
        ]
        exclude: ^(docs/|tasks\.py|tests/|src/virtual_gpu_lut_box/gpu_texture_stream/syphon\.py|src/virtual_gpu_lut_box/gpu_texture_stream/spout\.py)

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, src/virtual_gpu_lut_box]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        args: [--cov=virtual_gpu_lut_box, --cov-fail-under=50, tests/]
